[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[api]
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  network = "web"

[providers.file]
  filename = "./rules.toml"

[certificatesResolvers.lroland.acme]
  email = "louisroland1309@gmail.com"
  storage = "acme.json"
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.lroland.acme.httpChallenge]
    entryPoint = "http"
